# Generated by Django 3.2.18 on 2023-03-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyValueDataFrame',
            new_name='KeyValueDF',
        ),
    ]
