# Generated by Django 3.2.18 on 2023-03-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0002_rename_keyvaluedataframe_keyvaluedf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyValueDF',
            new_name='KeyValueDataFrame',
        ),
    ]
