# Generated by Django 3.2.18 on 2023-03-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0003_rename_keyvaluedf_keyvaluedataframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyvaluedataframe',
            name='file_name',
            field=models.CharField(default='NOFILENAME', max_length=200),
        ),
    ]
