# Generated by Django 3.2.18 on 2023-04-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconcile', '0005_keyvaluedataframe_sheet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvaluedataframe',
            name='sheet_name',
            field=models.CharField(default='Sheet1', max_length=50),
        ),
    ]
