# Generated by Django 3.2.18 on 2023-03-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_dataset_fileid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empcode', models.CharField(default='', max_length=10)),
                ('firstName', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
    ]
