# Generated by Django 3.2.18 on 2023-05-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValueDataFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='NOFILENAME', max_length=200)),
                ('sheet_name', models.CharField(default='Sheet1', max_length=50)),
                ('key', models.CharField(default='No_Column_Header', max_length=200)),
                ('val', models.CharField(default='No_Value', max_length=500)),
            ],
        ),
    ]
