# Generated by Django 3.2.18 on 2023-06-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findandextract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='nofile', max_length=200)),
                ('sheet_name', models.CharField(default='Sheet1', max_length=50)),
                ('header_index', models.CharField(default='0', max_length=2)),
                ('cond_andor', models.CharField(default='and', max_length=10)),
                ('cond_col_name', models.CharField(default='column_name', max_length=100)),
                ('cond_col_action', models.CharField(default='Equals', max_length=50)),
                ('cond_value', models.CharField(default='novalue', max_length=100)),
                ('cond_value_and', models.CharField(default='noandvalue', max_length=100)),
            ],
        ),
    ]
