# Generated by Django 3.2.18 on 2023-06-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findandextract', '0002_datafilters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafilters',
            old_name='header_index',
            new_name='primary_header_row',
        ),
        migrations.RemoveField(
            model_name='datafilters',
            name='cond_andor',
        ),
        migrations.RemoveField(
            model_name='datafilters',
            name='cond_col_action',
        ),
        migrations.RemoveField(
            model_name='datafilters',
            name='cond_col_name',
        ),
        migrations.RemoveField(
            model_name='datafilters',
            name='cond_value',
        ),
        migrations.RemoveField(
            model_name='datafilters',
            name='cond_value_and',
        ),
        migrations.RemoveField(
            model_name='datafilters',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='datafilters',
            name='sheet_name',
        ),
        migrations.AddField(
            model_name='datafilters',
            name='primary_conditions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datafilters',
            name='primary_file_name',
            field=models.CharField(default='NOFILENAME', max_length=200),
        ),
        migrations.AddField(
            model_name='datafilters',
            name='primary_sheet_name',
            field=models.CharField(default='Sheet1', max_length=100),
        ),
        migrations.AddField(
            model_name='datafilters',
            name='secondary_conditions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datafilters',
            name='secondary_file_name',
            field=models.CharField(default='NOFILENAME', max_length=200),
        ),
        migrations.AddField(
            model_name='datafilters',
            name='secondary_header_row',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='datafilters',
            name='secondary_sheet_name',
            field=models.CharField(default='Sheet1', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyvaluedataframe',
            name='sheet_name',
            field=models.CharField(default='Sheet1', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyvaluedataframe',
            name='val',
            field=models.TextField(),
        ),
    ]
