# Generated by Django 4.2.7 on 2024-06-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findandextract', '0007_keyvaluedataframe_display_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValueDataFrame_Display',
            fields=[
                ('key', models.CharField(default='No_Column_Header', max_length=200)),
                ('val', models.TextField()),
                ('uid', models.CharField(default='NOUID', max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
