# Generated by Django 4.2.7 on 2024-06-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findandextract', '0008_keyvaluedataframe_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyvaluedataframe_display',
            name='file_name',
            field=models.CharField(default='NOFILENAME', max_length=200),
        ),
        migrations.AddField(
            model_name='keyvaluedataframe_display',
            name='sheet_name',
            field=models.CharField(default='Sheet1', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyvaluedataframe_display',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
